In [24]:
# importing all the necessary modules

import pandas as pd
import numpy as np

## Step 1: Analyzing the RAW data and understanding the data.

> **Note:** We might need to use MS Excel to understand the data

In [25]:
cases = pd.read_csv('RAW_global_confirmed_cases.csv')
cases.head()

,Country/Region,Province/State,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,...,2/28/23,03-01-2023,03-02-2023,03-03-2023,03-04-2023,03-05-2023,03-06-2023,03-07-2023,03-08-2023,03-09-2023
0,Afghanistan,NaN,33.93911,67.709953,0,0,0,0,0,0,...,209322,209340,209358,209362,209369,209390,209406,209436,209451,209451
1,Albania,NaN,41.15330,20.168300,0,0,0,0,0,0,...,334391,334408,334408,334427,334427,334427,334427,334427,334443,334457
2,Algeria,NaN,28.03390,1.659600,0,0,0,0,0,0,...,271441,271448,271463,271469,271469,271477,271477,271490,271494,271496
3,Andorra,NaN,42.50630,1.521800,0,0,0,0,0,0,...,47866,47875,47875,47875,47875,47875,47875,47875,47890,47890
4,Angola,NaN,-11.20270,17.873900,0,0,0,0,0,0,...,105255,105277,105277,105277,105277,105277,105277,105277,105288,105288

In [26]:
cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289 entries, 0 to 288
Columns: 1147 entries, Country/Region to 03-09-2023
dtypes: float64(2), int64(1143), object(2)
memory usage: 2.5+ MB

In [27]:
cases.describe()

,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,...,2/28/23,03-01-2023,03-02-2023,03-03-2023,03-04-2023,03-05-2023,03-06-2023,03-07-2023,03-08-2023,03-09-2023
count,287.000000,287.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,289.000000,...,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02,2.890000e+02
mean,19.718719,22.182084,1.927336,2.273356,3.266436,4.972318,7.335640,10.134948,19.307958,21.346021,...,2.336755e+06,2.337519e+06,2.338173e+06,2.338805e+06,2.338992e+06,2.339187e+06,2.339387e+06,2.339839e+06,2.340460e+06,2.341073e+06
std,25.956609,77.870931,26.173664,26.270191,32.707271,45.523871,63.623197,85.724481,210.329649,211.628535,...,8.506608e+06,8.511285e+06,8.514488e+06,8.518031e+06,8.518408e+06,8.518645e+06,8.519346e+06,8.521641e+06,8.524968e+06,8.527765e+06
min,-71.949900,-178.116500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,4.072192,-32.823050,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04,1.456700e+04
50%,21.512583,20.939400,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05,1.032480e+05
75%,40.401784,89.224350,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,1.051998e+06,1.052122e+06,1.052247e+06,1.052382e+06,1.052519e+06,1.052664e+06,1.052664e+06,1.052926e+06,1.053068e+06,1.053213e+06
max,71.706900,178.065000,444.000000,444.000000,549.000000,761.000000,1058.000000,1423.000000,3554.000000,3554.000000,...,1.034435e+08,1.035339e+08,1.035898e+08,1.036487e+08,1.036508e+08,1.036470e+08,1.036555e+08,1.036909e+08,1.037558e+08,1.038027e+08

In [28]:
cases.isnull().sum()

Country/Region      0
Province/State    198
Lat                 2
Long                2
1/22/20             0
                 ...
03-05-2023          0
03-06-2023          0
03-07-2023          0
03-08-2023          0
03-09-2023          0
Length: 1147, dtype: int64

In [29]:
# finding the index of the NaN values in the dataset.
no_pos_data = [i for i in range(len(cases)) if cases.isnull().iloc[i, 2] and cases.isnull().iloc[i, 3]]
no_pos_data

# Task: Setting the values with the country's latitude and longitude values

# Step 1: Identify the data about these indexes
# cases.iloc[[53, 89], :]

[53, 89]

In [30]:
# Step 2: Since both countries have state/province values in the dataset, we can fill these values with either the above values or the values below.

# Note: If the country has no multiple state values, then we need to find the country's latitude and longitude values and then put them in the dataset.

cases.iloc[:, 2:4] = cases.iloc[:, 2:4].ffill()

In [31]:
cases.duplicated().sum()

np.int64(0)

## Step 2: After analyzing, the conclusion is that it needed to be converted and pre-processed for better representation.

### Step 2.1: Transposing the dataset, as we need all columns as rows and rows as columns.

In [32]:
cases = cases.transpose()
cases

,0,1,2,3,4,5,6,7,8,9,...,279,280,281,282,283,284,285,286,287,288
Country/Region,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,Australia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
Province/State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Australian Capital Territory,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Lat,33.93911,41.1533,28.0339,42.5063,-11.2027,-71.9499,17.0608,-38.4161,40.0691,-35.4735,...,-32.5228,41.377491,-15.3767,6.4238,14.058324,31.9522,39.9042,15.552727,-13.133897,-19.015438
Long,67.709953,20.1683,1.6596,1.5218,17.8739,23.347,-61.7964,-63.6167,45.0382,149.0124,...,-55.7658,64.585262,166.9592,-66.5897,108.277199,35.2332,116.4074,48.516388,27.849332,29.154857
1/22/20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
03-05-2023,209390,334427,271477,47875,105277,11,9106,10044125,446819,232619,...,1034303,251071,12014,552051,11526966,703228,535,11945,343135,264127
03-06-2023,209406,334427,271477,47875,105277,11,9106,10044957,446819,232619,...,1034303,251071,12014,552125,11526966,703228,535,11945,343135,264127
03-07-2023,209436,334427,271490,47875,105277,11,9106,10044957,446819,232619,...,1034303,251071,12014,552157,11526986,703228,535,11945,343135,264127
03-08-2023,209451,334443,271494,47890,105288,11,9106,10044957,447308,232619,...,1034303,251247,12014,552157,11526994,703228,535,11945,343135,264276
03-09-2023,209451,334457,271496,47890,105288,11,9106,10044957,447308,232974,...,1034303,251247,12014,552162,11526994,703228,535,11945,343135,264276

In [33]:
cases.iloc[0:2]

,0,1,2,3,4,5,6,7,8,9,...,279,280,281,282,283,284,285,286,287,288
Country/Region,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,Australia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
Province/State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Australian Capital Territory,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Renaming the index values for better readability and code writing.

In [34]:
# renaming the 'Country/Region' and 'Province/State'

cases = cases.rename(index={
    'Country/Region': 'Country',
    'Province/State': 'State'
})

### Step 2.2: Make a dictionary for all the countries that have data values spreaded in the different states, so we can identify and combine them under the country name. 

### This code analyzes a dataset (`cases`) where **countries and their states/provinces are stored across columns** rather than in a traditional tabular format.  

### Its main goal is to **identify which countries have state-level data** and to **group all corresponding state columns under each country**.

In [35]:
# Making a dictionary for all the countries that have states mentioned in the dataset.
# This dictionary will be used for removing the state row and combining the data in the country column
def stateFinder(cases):

    # Finding the index of the states whose value is not null.
    notna_indexes = [i for i in cases.columns if pd.notna(cases.iloc[1, i])]
    
    countryWithStates = {}
    for i in notna_indexes:
        Country = cases.iloc[0, i]
        States = []
        for j in cases.columns:
            if Country == cases.iloc[0, j]:
                States.append(j)
        countryWithStates.update({Country: States})

    return countryWithStates

cws_c = stateFinder(cases)
for key, values in cws_c.items():
    print(f"{key} : {values}")

Australia : [9, 10, 11, 12, 13, 14, 15, 16]
Canada : [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55]
China : [59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]
Denmark : [103, 104, 105]
France : [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]
Netherlands : [196, 197, 198, 199, 200]
New Zealand : [201, 202, 203]
United Kingdom : [264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278]

In [36]:
cases.iloc[0,:].value_counts().head(10)

Country
China             34
Canada            16
United Kingdom    15
France            12
Australia          8
Netherlands        5
New Zealand        3
Denmark            3
Albania            1
Armenia            1
Name: count, dtype: int64

### Step 2.3: Now, we can combine all the states' data for each country.

### When aggregating data by country, geographic coordinates (latitude and longitude) are averaged, while all other numeric fields are summed to produce a single consolidated country-level record.

In [37]:
cases.drop('State', axis=0, inplace=True)

In [38]:
for country, states in cws_c.items():
    position = cases.iloc[1:3, states].mean(axis=1)
    total = cases.iloc[3:, states].sum(axis=1)
    final = pd.concat([position, total])
    cases.iloc[1:, states[0]] = final

for country, states in cws_c.items():
    cases.drop(states[1:], axis=1, inplace=True)

In [39]:
# Make the country name a column name and drop the country row.
cases.columns = cases.iloc[0]
cases.drop('Country', axis=0, inplace=True)

In [40]:
# Assign column and index names, for better understanding
# cases.columns.name = 'Countries'
# cases.index.name = 'Attributes'

In [42]:
# Temp code: Analyzing the combied data for validation.
countries = list(cws_c.keys())
cases.loc[:, countries]
# cases

Country,Australia,Canada,China,Denmark,France,Netherlands,New Zealand,United Kingdom
Lat,-32.106275,47.612219,32.8525,63.2878,6.4253,21.40884,-27.0639,22.42456
Long,141.355487,-79.759187,111.089121,-13.3381,-9.839634,-52.99206,-51.5863,-42.022004
1/22/20,0,0,548,0,0,0,0,0
1/23/20,0,2,643,0,0,0,0,0
1/24/20,0,3,920,0,2,0,0,0
...,...,...,...,...,...,...,...,...
03-05-2023,11385534,4609751,4903524,3450336,39839090,8710897,2236111,24629840
03-06-2023,11385534,4611428,4903524,3450587,39847236,8710897,2236113,24629840
03-07-2023,11385534,4612219,4903524,3450757,39854299,8712835,2236113,24629846
03-08-2023,11385534,4613054,4903524,3450897,39860410,8712835,2236113,24629922
03-09-2023,11399460,4617095,4903524,3451036,39866718,8712835,2236114,24658705

In [44]:
# cases.reset_index(inplace=True)
# cases.drop(['level_0', 'index'], axis=1, inplace=True)

cases.index.name = None
cases.columns.name = None
cases

,index,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
0,Lat,33.93911,41.1533,28.0339,42.5063,-11.2027,-71.9499,17.0608,-38.4161,40.0691,...,-32.5228,41.377491,-15.3767,6.4238,14.058324,31.9522,39.9042,15.552727,-13.133897,-19.015438
1,Long,67.709953,20.1683,1.6596,1.5218,17.8739,23.347,-61.7964,-63.6167,45.0382,...,-55.7658,64.585262,166.9592,-66.5897,108.277199,35.2332,116.4074,48.516388,27.849332,29.154857
2,1/22/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1/23/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
4,1/24/20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,03-05-2023,209390,334427,271477,47875,105277,11,9106,10044125,446819,...,1034303,251071,12014,552051,11526966,703228,535,11945,343135,264127
1141,03-06-2023,209406,334427,271477,47875,105277,11,9106,10044957,446819,...,1034303,251071,12014,552125,11526966,703228,535,11945,343135,264127
1142,03-07-2023,209436,334427,271490,47875,105277,11,9106,10044957,446819,...,1034303,251071,12014,552157,11526986,703228,535,11945,343135,264127
1143,03-08-2023,209451,334443,271494,47890,105288,11,9106,10044957,447308,...,1034303,251247,12014,552157,11526994,703228,535,11945,343135,264276
1144,03-09-2023,209451,334457,271496,47890,105288,11,9106,10044957,447308,...,1034303,251247,12014,552162,11526994,703228,535,11945,343135,264276

In [45]:
def parse_date(date):
    if pd.isna(date):
        return pd.NaT

    date = str(date).strip()

    if '/' in date:
        return pd.to_datetime(date, format="%m/%d/%y", errors="coerce")
    elif '-' in date:
        return pd.to_datetime(date, format="%m-%d-%Y", errors="coerce")
    else:
        return pd.NaT


# cases['index'].iloc[2:] = cases['index'].iloc[2:].apply(parse_date).dt.strftime("%d-%m-%Y")
cases.iloc[2:, 0] = cases.iloc[2:, 0].apply(parse_date).dt.strftime("%d-%m-%Y")
# cases['index'].iloc[2:].apply(parse_date).dt.strftime("%d-%m-%Y")
cases['index']

0              Lat
1             Long
2       22-01-2020
3       23-01-2020
4       24-01-2020
           ...
1140    05-03-2023
1141    06-03-2023
1142    07-03-2023
1143    08-03-2023
1144    09-03-2023
Name: index, Length: 1145, dtype: object

In [46]:
cases = cases.rename(columns={'index':'Date'})
cases

,Date,Afghanistan,Albania,Algeria,Andorra,Angola,Antarctica,Antigua and Barbuda,Argentina,Armenia,...,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West Bank and Gaza,Winter Olympics 2022,Yemen,Zambia,Zimbabwe
0,Lat,33.93911,41.1533,28.0339,42.5063,-11.2027,-71.9499,17.0608,-38.4161,40.0691,...,-32.5228,41.377491,-15.3767,6.4238,14.058324,31.9522,39.9042,15.552727,-13.133897,-19.015438
1,Long,67.709953,20.1683,1.6596,1.5218,17.8739,23.347,-61.7964,-63.6167,45.0382,...,-55.7658,64.585262,166.9592,-66.5897,108.277199,35.2332,116.4074,48.516388,27.849332,29.154857
2,22-01-2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,23-01-2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
4,24-01-2020,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,05-03-2023,209390,334427,271477,47875,105277,11,9106,10044125,446819,...,1034303,251071,12014,552051,11526966,703228,535,11945,343135,264127
1141,06-03-2023,209406,334427,271477,47875,105277,11,9106,10044957,446819,...,1034303,251071,12014,552125,11526966,703228,535,11945,343135,264127
1142,07-03-2023,209436,334427,271490,47875,105277,11,9106,10044957,446819,...,1034303,251071,12014,552157,11526986,703228,535,11945,343135,264127
1143,08-03-2023,209451,334443,271494,47890,105288,11,9106,10044957,447308,...,1034303,251247,12014,552157,11526994,703228,535,11945,343135,264276
1144,09-03-2023,209451,334457,271496,47890,105288,11,9106,10044957,447308,...,1034303,251247,12014,552162,11526994,703228,535,11945,343135,264276

In [47]:
# Selecting the list of countries for the visualization task.

# countries = ['India', 'Australia', 'China', 'Japan', 'Canada', 'US', 'United Kingdom', 'United Arab Emirates', 'Germany', 'France', 'Russia', 'Singapore', 'New Zealand']

cases.to_csv('Covid_19_Cases_Cleaned.csv')